### ISSUE TITLE
Prefix?

### ISSUE THREAD

**Issue by SpaceLeft** [costaluu/Sloth-Music#6]
Where the prefix?

**Comment by yagomichalak** [comment]
The prefix will always be **s[index]**, and you can change the index in the **dev** script found in **package.json**, you'll see that the script ends with 0 0, you change this first 0 to something of your preference, like 3 for a **s3** prefix

**Comment by SpaceLeft** [comment]
give me ur discord need connect with you.

**Comment by costaluu** [comment]
@SpaceLeft as @yagomichalak said you can just change the parameter here then you will have s[index] as prefix:

https://github.com/costaluu/Sloth-Music/blob/420bd40ce2ff6c4fb0ed3f0dfc15c53a35edcfed/package.json#L7

if you really want to change it to a custom prefix, check the messageCreate event:

https://github.com/costaluu/Sloth-Music/blob/420bd40ce2ff6c4fb0ed3f0dfc15c53a35edcfed/src/Events/messageCreate.ts#L31
